apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  limits:
    resources:
      cpu: 20k
  provider:
    securityGroupSelector:
      karpenter.sh/discovery: eks-cluster-sg-ddosudpsimu-us-west-2
    subnetSelector:
      karpenter.sh/discovery: SubnetPublic
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - c6g.xlarge
    - c6g.2xlarge
    - c6g.4xlarge
    - c6g.8xlarge
    - c6g.12xlarge
    - c6g.16xlarge
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  ttlSecondsAfterEmpty: 30
